/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swtienda;

import gestion.GestiónProductos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import negocio.Producto;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;

/**
 *
 * @author valentina
 */
public class Inventario extends javax.swing.JFrame implements ActionListener, ItemListener
{

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inventario");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Regresar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Organizar por:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    GestiónProductos gestiProd=new GestiónProductos();
    
    
    private DefaultTableModel modelo;
    private Ppal ppal;
    
    //Métodos de servicio
    private void Listener()
    {
        
        this.jButton2.addActionListener(this);
        this.jComboBox1.addItemListener(this);
    }
    
    //Evento-Acción
    
    public Inventario(Ppal ppal)
    {
        initComponents();
        this.setVisible(true);
        
        this.setLocationRelativeTo(null);
        this.Listener();
        this.modelo=null;
        this.ppal=ppal;
        this.modelaTabla();
        this.LlenaCombo();
        this.traeProductos();
        
    }
    private void traeProductos()
    {
      ArrayList<Producto> produs=gestiProd.getTodos();
      
      for(Producto prod: produs)
      {
          Vector fila=new Vector();
          fila.add(prod.getCodigo());
          fila.add(prod.getNombre());
          fila.add(prod.getPrecioCompra());
          fila.add(prod.getPrecioVenta());
          fila.add(prod.getExistencias());
          
          this.modelo.addRow(fila);
      }
    }
    
    private void accionBtnRegresar() 
    {
        this.setVisible(false);
        this.ppal.setVisible(true);
    }
    
    private void LlenaCombo()
    {
        this.jComboBox1.addItem("Seleccione");
        this.jComboBox1.addItem("Producto");
        this.jComboBox1.addItem("Precio de Compra");
        this.jComboBox1.addItem("Precio de Venta");
        this.jComboBox1.addItem("Código");
        this.jComboBox1.addItem("Existencias");
    }
    
    private void modelaTabla()
    {
        this.modelo= new DefaultTableModel();
        this.jTable1.setModel(modelo);
        
        this.modelo.addColumn("Código");
        this.modelo.addColumn("Producto");
        this.modelo.addColumn("Precio de Compra");
        this.modelo.addColumn("Precio de venta");
        this.modelo.addColumn("Existencias");
        
    }
    
    private void organizar(int op)
    {
       ArrayList<Producto> produs=gestiProd.getTodos(); 
        
        if(op==4) 
            Collections.sort(produs,Comparator.comparing(Producto::getCodigo));
        if(op==1) 
            Collections.sort(produs,Comparator.comparing(Producto::getNombre));
        if(op==2) 
            Collections.sort(produs,Comparator.comparing(Producto::getPrecioCompra));
        if(op==3) 
            Collections.sort(produs,Comparator.comparing(Producto::getPrecioVenta)); 
        if(op==5) 
            Collections.sort(produs,Comparator.comparing(Producto::getExistencias)); 
        
        this.ord(produs);
    }
    
    private void ord(ArrayList <Producto> produs)
    {
      this.limpiar();
      for(Producto prod: produs)
      {
          Vector fila=new Vector();
          fila.add(prod.getCodigo());
          fila.add(prod.getNombre());
          fila.add(prod.getPrecioCompra());
          fila.add(prod.getPrecioVenta());
          fila.add(prod.getExistencias());
          
          this.modelo.addRow(fila);
      }
    }
    
    private void limpiar()
    {
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i );
        }
    }
    //====================================================
    @Override
    public void actionPerformed(ActionEvent evento)
    {
        
        if(evento.getSource()==this.jButton2)
        {
            this.accionBtnRegresar();
        }
        
    }

    @Override
    public void itemStateChanged(ItemEvent e) 
    {
      if(e.getSource()==this.jComboBox1)
        {
            int i=this.jComboBox1.getSelectedIndex();
            if(i>0)
                this.organizar(i);
        } 
    }

   
}

