/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swtienda;

import gestion.GestiónClientes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import negocio.Clientes;

/**
 *
 * @author valentina
 */
public class PanelClientes extends javax.swing.JPanel  implements ActionListener, ItemListener, MouseListener
{

    /**
     * Creates new form PanelClientes
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jButton3.setText("Traer Clientes");

        jLabel1.setText("Identificación");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nombre");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Tipo");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToggleButton1.setText("Nuevo");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jToggleButton1.isSelected())
       {
           this.toogle();
       }
       else
       {
           this.agregaCliente();
       }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    GestiónClientes gestorClie;
    ArrayList<Clientes> listaClie; 
    private DefaultTableModel modelo;
    
    TableRowSorter<TableModel> elQueOrdena; 
    
    public PanelClientes() 
    {
        initComponents();
        this.setBounds(0, 0 , 650, 270);
        this.gestorClie =new GestiónClientes();
        
        this.listaClie=new ArrayList<>();
        this.listaClie = gestorClie.getTodos();
        this.LlenaCombo();
        this.modelo=new DefaultTableModel();
        
        this.modelaTabla();
        this.Listener();
    }
    
    private void Listener()
    {
        this.jButton3.addActionListener(this);
        this.jToggleButton1.addItemListener(this); 
        this.jComboBox1.addItemListener(this);
        this.jTable1.addMouseListener(this);
    }
    
    private void LlenaCombo()
    {
        this.jComboBox1.addItem("Seleccione");
        this.jComboBox1.addItem("Persona");
        this.jComboBox1.addItem("Empresa");
    }
    
    private void agregaCliente()
    {
        boolean existeCodigo;
                
        this.jToggleButton1.setText("Nuevo");
        Clientes clie=null;
        if (!(this.jTextField2.getText().equals("")) && !(this.jTextField1.getText().equals("")) && this.jComboBox1.getSelectedIndex()>0)
            {
              String ID = this.jTextField2.getText();
              String nombre = this.jTextField1.getText();
              existeCodigo=this.gestorClie.verificarID(ID);
              
            if(!existeCodigo)
            {
                String tipo = (String)this.jComboBox1.getSelectedItem();
                clie = new Clientes(ID, nombre, tipo);

                listaClie.add(clie);
                this.gestorClie.recargArchivo(listaClie);
                JOptionPane.showMessageDialog(null, "cliente añadido");
                this.jTextField1.setText("");
                this.jTextField2.setText("");
                this.jComboBox1.setSelectedItem("Seleccione");
             }
            else
            {
                JOptionPane.showMessageDialog(null, "ESE ID YA EXISTE..!!!"); 
                this.jTextField2.setText("");
                this.jTextField2.requestFocus();
            }
            } 
        else
            {
              JOptionPane.showMessageDialog(null, "no ingreso todos los parametros \n"
                      + "cliente no añadido");

            }
        this.traeProductos(clie);
        
        
    }
    
    private void traeProductos(Clientes clie)
    {
          Vector fila=new Vector();
          fila.add(clie.getID());
          fila.add(clie.getNombre());
          fila.add(clie.getTipo());
          
          
          this.modelo.addRow(fila);
      
    }
    
    private void modelaTabla()
    {
        this.jTable1.setModel(modelo);
        this.elQueOrdena= new TableRowSorter<TableModel>(this.jTable1.getModel());
        this.modelo.addColumn("ID");
        this.modelo.addColumn("Nombre");
        this.modelo.addColumn("Tipo");
        
        this.jTable1.setRowSorter(elQueOrdena);
        ArrayList <RowSorter.SortKey> SortKey=new ArrayList<>();
        
        elQueOrdena.setSortKeys(SortKey);
        elQueOrdena.sort();
        
    }
    
    private void toogle()
    {
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jComboBox1.setSelectedIndex(0);
        this.jToggleButton1.setText("Guardar");
        this.jTextField2.requestFocus();
    }
    
    private void traeTodos()
    {
      this.limpiar();
      
      for(Clientes cli: this.listaClie)
      {
          Vector fila=new Vector();
          fila.add(cli.getID());
          fila.add(cli.getNombre());
          fila.add(cli.getTipo());
          
          
          this.modelo.addRow(fila);
      }
    }
    
    private void limpiar()
    {
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i );
        }
    }
    
    private void tablaPone()
    {
        int seleccionada;
        String dato;
        seleccionada=this.jTable1.getSelectedRow();
        if(seleccionada>=0)
        {
            //hago la vuelta
            dato=this.jTable1.getValueAt(seleccionada,0).toString();
            this.jTextField2.setText(dato);
            dato=this.jTable1.getValueAt(seleccionada,1).toString();
            this.jTextField1.setText(dato);
            dato=this.jTable1.getValueAt(seleccionada,2).toString();
            this.jComboBox1.setSelectedItem(dato);
        }
     
    }
    @Override
    public void actionPerformed(ActionEvent e) 
    {
       if(e.getSource()==this.jButton3)
        {
            this.traeTodos();
        }
       
    }

    @Override
    public void itemStateChanged(ItemEvent e) 
    {
       
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
       if(e.getSource()==this.jTable1)
        {
            this.tablaPone();
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
    
}
