/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swtienda;

import gestion.GestiónProveedores;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import negocio.Proveedores;

/**
 *
 * @author valentina
 */
public class PanelProveedores extends javax.swing.JPanel implements ActionListener, MouseListener
{

    /**
     * Creates new form PanelProveedores
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));

        jButton4.setText("Traer Proveedores");
        jButton4.setActionCommand("");

        jLabel5.setText("Identificación");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Nombre");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToggleButton2.setText("Nuevo");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jToggleButton2.isSelected())
       {
           this.toogle();
       }
       else
       {
           this.agregaCliente();
       }
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    GestiónProveedores gestorProv;
    ArrayList<Proveedores> listaProv;
    private DefaultTableModel modelo;
    TableRowSorter<TableModel> elQueOrdena; 
    private Ppal ppal;
    
    public PanelProveedores() 
    {
        initComponents();
        this.setBounds(0, 0 , 650, 270);
        this.gestorProv= new GestiónProveedores();
        
        this.listaProv = new ArrayList<>();
        this.listaProv = gestorProv.getTodos();
        
        this.modelo=new DefaultTableModel();
        this.modelaTabla();
        this.Listener();
    }
    
     private void Listener()
    {
        this.jButton4.addActionListener(this);
        this.jToggleButton2.addActionListener(this);    
        this.jTable3.addMouseListener(this);
    }
     
    private void toogle()
    {
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jToggleButton2.setText("Guardar");
        this.jTextField4.requestFocus();
    }
    
    private void agregaCliente()
    {
        boolean existeCodigo, existeNombre;
                
        this.jToggleButton2.setText("Nuevo");
        Proveedores prove=null;
        if (!(this.jTextField4.getText().equals("")) && !(this.jTextField3.getText().equals("")))
            {
                String ID = this.jTextField4.getText();
                String nombre = this.jTextField3.getText();
                existeCodigo=this.gestorProv.verificarID(ID);

              if(!existeCodigo)
              {
                 existeNombre=this.gestorProv.verificarNombre(nombre);
                 if(!existeNombre)
                 {

                  prove = new Proveedores(ID, nombre);

                  listaProv.add(prove);
                  this.gestorProv.recargArchivo(listaProv);
                 // this.comp.llenarcombos();
                  JOptionPane.showMessageDialog(null, "Proveedor añadido");
                  this.jTextField4.setText("");
                  this.jTextField3.setText("");
                 }
                 else
                 {
                  JOptionPane.showMessageDialog(null, "ESE NOMBRE YA EXISTE..!!!");
                  this.jTextField3.setText("");
                  this.jTextField3.requestFocus();
                 }
                }
               else
               {
                   JOptionPane.showMessageDialog(null, "ESE ID YA EXISTE..!!!"); 
                   this.jTextField3.setText("");
                   this.jTextField4.requestFocus();
               }
            
            }
        else
            {
              JOptionPane.showMessageDialog(null, "no ingreso todos los parametros \n"
                      + "cliente no añadido");

            }
        this.traeProductos(prove);
        
    }
    
    private void traeProductos(Proveedores clie)
    {
          Vector fila=new Vector();
          fila.add(clie.getID());
          fila.add(clie.getNombre());
          
          this.modelo.addRow(fila);
      
    }
    
    private void limpiar()
    {
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i );
        }
    }
    
    private void modelaTabla()
    {
        this.jTable3.setModel(modelo);
        this.elQueOrdena= new TableRowSorter<TableModel>(this.jTable3.getModel());
        this.modelo.addColumn("ID");
        this.modelo.addColumn("Nombre");
        
        this.jTable3.setRowSorter(elQueOrdena);
        ArrayList <RowSorter.SortKey> SortKey=new ArrayList<>();
        
        elQueOrdena.setSortKeys(SortKey);
        elQueOrdena.sort();
    }
    
    private void traeTodos()
    {
      this.limpiar();
      
      for(Proveedores cli: this.listaProv)
      {
          Vector fila=new Vector();
          fila.add(cli.getID());
          fila.add(cli.getNombre());
          
          
          this.modelo.addRow(fila);
      }
    }
    
    private void tablaPone()
    {
        int seleccionada;
        String dato;
        seleccionada=this.jTable3.getSelectedRow();
        if(seleccionada>=0)
        {
            //hago la vuelta
            dato=this.jTable3.getValueAt(seleccionada,0).toString();
            this.jTextField3.setText(dato);
            dato=this.jTable3.getValueAt(seleccionada,1).toString();
            this.jTextField4.setText(dato);
            
        }
     
    }
    
    @Override
    
    public void actionPerformed(ActionEvent e) 
    {
        if(e.getSource()==this.jButton4)
        {
            this.traeTodos();
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
      }

    @Override
    public void mousePressed(MouseEvent e) {
        if(e.getSource()==this.jTable3)
        {
            this.tablaPone();
        }
       }

    @Override
    public void mouseReleased(MouseEvent e) {
        }

    @Override
    public void mouseEntered(MouseEvent e) {
        }

    @Override
    public void mouseExited(MouseEvent e) {
        }
}
